[project]
name = "mcp-server-weather"
version = "0.1.0"
description = "A weather tool server using the MCP framework to provide weather data from the Open-Meteo API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.15.0",
]
